#debug=true
debug: false
#server.port=80
#前缀相同的配置项，idea会自动进行归纳
server:
 port: 8001
 servlet:
   context-path: /
 thymeleaf:
   cache: false
spring:
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd HH:mm;ss SSS
    time-zone: GMT+8
#    serialization: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scott?useUnicode=true&characterEncoding=utf-8
    username: root
    password: sa1234
    #数据库类型为mysql
    dbType: mysql
    #启动时初始化5个连接
    initialSize: 20
    #最小空闲连接5个
    minIdle: 5
    #最大连接数量20
    maxActive: 20
    #获取连接等待时间60秒，超出报错
    maxWait: 60000
    #每60秒执行一次连接回收器
    timeBetweenEvictionRunsMillis: 60000
    #5分钟内没有任何操作的空闲连接会被回收
    minEvictableIdleTimeMillis: 300000
    #验证连接有效性的SQL
    validationQuery: select 'x'
    #空闲时校验，建议开启
    testWhileIdle: true
    #使用中是否校验有效性，推荐关闭
    testOnBorrow: false
    #归还连接时校验有效性，推荐关闭
    testOnReturn: false
    poolPreparedStatements: false
    #设置过滤器，stat用于接收状态，wall用于防止SQL注入,logback则说明使用logback日志输出
    filters: stat,wall,logback
    #统计所有数据源状态
    useGlobalDataSourceStat: true
    #sql合并统计，与设置慢SQL时间为500毫秒
    connectionProperties=druid.stat.mergeSql: true;druid.stat.slowSqlMillis=500
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /duMQ
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
logging:
  level:
    com.du.myspringboot.mapper : debug

